# Generated by Django 5.1.5 on 2025-02-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0002_alter_user_phone"),
    ]

    operations = []
