# Generated by Django 5.1.5 on 2025-01-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_photo_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
