# Generated by Django 5.1.5 on 2025-02-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_task_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="geo",
        ),
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="album",
            name="user",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="album",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="post",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company",
        ),
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
        migrations.DeleteModel(
            name="Geo",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="Album",
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
